### ISSUE TITLE
Add support for type erasures

### ISSUE THREAD

**Issue by arv** [codemix/flow-runtime#169]
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

Every function and binding gets tested for its type.

---

### What is the expected behaviour?

Only functions and bindings that cannot be proven to already be correct needs to test the types.

For example, if the code is a Module, only the entry points should need to have type assertions (not entirely true, if there are `any` types involved there are more cases that needs checks).

For example:

```js
export function f(x: number) {
  return g(1);
}
​
function g(x: number) : number {
  return x;
}
```

`g` does not need any assertions since the only way to get there is through `f` which already does the assertion.

Motivation: Performance. This would allow most code to ship with `flow-runtime` to production without any real performance issues.

**Comment by phpnode** [comment]
hey @arv, we actually went down this road with [babel-plugin-typecheck](https://github.com/codemix/babel-plugin-typecheck) which removes any typechecks it can prove unnecessary at compile time. The problem is that you basically have to reinvent Flow proper to do this with any degree of certainty. It's not impossible but it's really a lot of work. Another alternative would be to have a mode that produces checks only on arguments to exported or specially commented functions
