### ISSUE TITLE
TypeAliasing not working for functions of a Class

### ISSUE THREAD

**Issue by RiyanshKarani011235** [codemix/flow-runtime#41]
This is a:

 - [x] Bug Report

Which concerns:

 - [x] flow-runtime
 - [x] babel-plugin-flow-runtime

---

### What is the current behaviour?

basically, I think there is an issue with Type Aliasing (please correct me if I am wrong).

    // @flow-runtime

    type __foo__ = (param: number) => string;

    class ParseClass extends {
        constructor() {
            (this.foo: __foo__);
        }
    }

    class P extends ParseClass {
        foo() {
            // do nothing
        }
    }

    new P().foo();

---

### What is the expected behaviour?

According to my understanding, the following code should not work, because the TypeAlias of the function `foo` implemented in the class `P` is different than `__foo__`. So ideally, flow should throw an error.

---

### Which package versions are you using?

I am using the `"babel-plugin-flow-runtime": "^0.2.1"` package installed via npm, and putting it in my  `.babelrc` file as 

    "plugins": [
        ["flow-runtime", {
            "assert": true,
            "annotate": true
        }]
    ]

**Comment by phpnode** [comment]
The problem here is that we cannot reliably infer the argument types and return type of unannotated functions - we have to treat them as `Any<Function>` otherwise perfectly valid code (which Flow itself can infer correctly) will cause a type error. If you add an annotation to the method, like `foo (): void {}`, you should get the error you're looking for.
