### ISSUE TITLE
Flow's type definitions aren't 100% accurate

### ISSUE THREAD

**Issue by ryyppy** [codemix/flow-runtime#46]
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [X] Question
 - [ ] Other

Which concerns:

 - [X] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validatosr
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

```
const err: Error = new Error('hello');

// => flow-runtime will report a type mismatch
```

---

### What is the expected behaviour?

`err` should typecheck
---

### Which package versions are you using?

Current version used by the `/try` web interface

**Comment by phpnode** [comment]
It's happening because Flow's type definitions for `Error` are incorrect, and we're importing those types using `flow-runtime-cli` in the documentation site. If you don't use `flow-runtime-cli` you won't get this issue.
I will fix this particular example soon, but an unfortunate consequence of using Flow's type definitions is that a number of them seem to be slightly out of sync with reality. If would be good to get the broken definitions fixed in Flow too.

**Comment by phpnode** [comment]
Turns out we weren't respecting static call properties correctly so this was failing even given a compliant environment, should be fixed now.

**Comment by ryyppy** [comment]
Oh that's actually a good thing that we can also do some reality checks for the current flow-types
