### ISSUE TITLE
Type exports not stripped from imported node modules

### ISSUE THREAD

**Issue by seveibar** [codemix/flow-runtime#55]
This is a:

 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [X] babel-plugin-flow-runtime
 - [ ] flow-runtime-validatosr
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

Importing types from `node_modules` causes `SyntaxError`.

[See example repository](https://github.com/seveibar/flow-runtime-issue-import-module).

```bash
yarn install
yarn build
yarn start
```

---

**Setup**

Given a `node_module` with type exports,

```javascript
// @flow
export type Animal = {
  name: string,
  hasLegs: bool
};
```

And a source file...

```javascript
// @flow
import type { Animal } from 'animals';

const c:any = {
  name: 'Dog',
  hasLegs: 'yes', // this is not the right type (should be bool)
}

console.log((c:Animal).id);
```

Results in invalid export,

```
export type Animal = {
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/seve/workspace/flow-runtime-issue/dist/index.js:3:16)
    at Module._compile (module.js:571:32)
```

---

### What is the expected behaviour?

Remove types from imported `node_modules`.

---

### Which package versions are you using?

```javascript
"dependencies": {
    "animals": "file:animals",
    "babel-cli": "^6.23.0",
    "babel-core": "^6.23.1",
    "babel-plugin-flow-runtime": "^0.5.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.23.0",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-preset-stage-1": "^6.22.0"
  }
```

The babel configuration is as follows,
```javascript
"babel": {
    "presets": [
      "stage-1"
    ],
    "plugins": [
      [ "transform-flow-strip-types" ],
      [ "flow-runtime" ],
      ["transform-es2015-modules-commonjs"]
    ]
}
```

---

A workaround is to use the preferred method of type imports with the `flow-typed` directory. (i didn't personally test this)

**Comment by phpnode** [comment]
@seveibar thanks for filing the issue, unfortunately this isn't something that can be sensibly fixed because babel operates on strings of source code, not "files", "folders" or "projects" so it doesn't have the infrastructure to allow introspection of imports or requires. In this case we expect all `node_modules` to be compiled, as that is in line with how the ecosystem works.

**Comment by bradennapier** [comment]
Unfortunately this makes flow-runtime, for the most part, useless at this point.

You can not ignore node_modules or else flow-typed will break because it doesnt generate stubs for node_modules that define types, for example.

you can not use flow-runtime and flow together really in any useable way at this point :( 

I know your time is limited, but perhaps a notice about the incompatibilities and/or requesting someone to maintain the library / makea notice that this library is now depreciated as it does not work in the graphql ecosystem anymore.
