### ISSUE TITLE
Question about type assertion 

### ISSUE THREAD

**Issue by amilajack** [codemix/flow-runtime#7]
Will the following code throw an error?

```js
const some = {}
console.log(some + '') // <- does it throw error here?
```

**Comment by phpnode** [comment]
This won't throw because there are no type annotations, at the moment this project doesn't do any static inference so only explicitly typed code will throw. This could be fixed by leveraging `flow suggest ./filename.js` to give us this missing type info, but I'm not really sure whether that's desirable yet - I don't want to do the things that Flow can already do, and Flow will catch this bug at compile time.
