### ISSUE TITLE
Flow type-comment syntax not supported

### ISSUE THREAD

**Issue by r24y** [codemix/flow-runtime#97]
This is a:

 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [X] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

Flow permits a ["type-comment" syntax](https://flow.org/blog/2015/02/20/Flow-Comments/) for using specially-formatted comments to annotate Flow code. For example, the type annotations for `x` and `y` here are equivalent:

```js
let x: string;
let y/*: string */;
```

I've started adopting the comment syntax since I'm working in a shared codebase and don't want to upset my coworkers by introducing the full Flow syntax.

The below code yields no errors when [run in the REPL](https://codemix.github.io/flow-runtime/#/try):
```js
type Thing = {
  id: string | number;
  name: string;
};

const widget/*: Thing*/ = {
  id: false,
  name: 'Widget'
};

console.log(widget);
```
---

### What is the expected behaviour?

The above example should have the same behavior as the default code displayed in the REPL:

```js
type Thing = {
  id: string | number;
  name: string;
};

const widget: Thing = {
  id: false,
  name: 'Widget'
};

console.log(widget);
```
---

### Which package versions are you using?

`babel-plugin-flow-runtime@0.10.0`

**Comment by phpnode** [comment]
The issue here is that Babylon (babel's parser) doesn't recognise these comments as being anything special, so it doesn't parse them. It's technically possible for us to detect them and parse them ourselves but it is a huge amount of work, a maintenance burden and slow as well. Probably your best bet is to use [flow-parser](https://www.npmjs.com/package/flow-parser) itself, using it like this in your `.babelrc`:

```json
{
  "parserOpts": {
    "parser": "flow-parser"
  },
  "plugins": []
}
```


I haven't tried this, in theory it should work but there are some AST differences between what Babylon produces and what Flow produces that may cause problems (there are ongoing efforts to normalize them). You may need to write an intermediate compatibility layer that smoothes over those differences, see https://github.com/codemix/flow-runtime/blob/master/packages/flow-runtime-cli/src/parseFileWithFlow.js for something similar.

**Comment by r24y** [comment]
Thanks for taking the time to look into this!
